version: '3.8'

services:
  api:
    build: ./api
    env_file: .env
    depends_on:
      - db

  db:
    build: ./db
    env_file: .env
    ports:
      - "3306:3306"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
